[phases.setup]
nixPkgs = ["nodejs_20", "python3", "cairo", "pango", "libjpeg", "giflib", "librsvg", "pixman"]

[phases.install]
cmds = ["cd server && npm install"]

[phases.build]
cmds = ["cd server && npm run build"]

[start]
cmd = "cd server && node dist/index.js"
